version: '3.4'

services:
  fastapiproject:
    image: fastapiproject
    environment:
      - DB_HOST=localhost
      - DB_PORT=5433
      - DB_NAME=product
      - DB_USER=postgres
      - DB_PASS=root
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
  
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=product
    ports:
      - "5433:5432"