version: '3.4'

services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=product
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapiproject:
    image: fastapiproject
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=product
      - DB_USER=postgres
      - DB_PASS=root
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
volumes:
  postgres_data: