version: '3.4'

services:
  fastapiproject:
    image: fastapiproject
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
